mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.springboot.demo02.mybatis.entity
server:
  port: 8080
spring:
  application:
    name: demo02
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    name: test
    password: ylmn750716
    url: jdbc:mysql://localhost:3306/test
    username: root
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
